//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeJuego.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class C_tbAtaques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tbAtaques()
        {
            this.C_tbPokemon = new HashSet<C_tbPokemon>();
        }
    
        public int intAtaque { get; set; }
        public string strNombreAtaque { get; set; }

        [Range(0, 70, ErrorMessage = "El daño total no puede superar los 70 puntos, tu sabes, solo por sio acaso")]
        public int intDaño { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tbPokemon> C_tbPokemon { get; set; }
    }
}
