//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeJuego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tbPokemon
    {
        public int intPokemon { get; set; }
        public string strNombrePokemon { get; set; }
        public string strImagen { get; set; }
        public byte tnyVida { get; set; }
        public int intTipoPokemon { get; set; }
        public int intAtaque { get; set; }
        public int intAtaqueEsp { get; set; }
    
        public virtual C_tbAtaqueEspecial C_tbAtaqueEspecial { get; set; }
        public virtual C_tbAtaques C_tbAtaques { get; set; }
        public virtual C_tbTipoPokemon C_tbTipoPokemon { get; set; }
    }
}
