//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeJuego.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class C_tbPokemon
    {
        public int intPokemon { get; set; }
        public string strNombrePokemon { get; set; }

        [Required(ErrorMessage = "Se te recomienda encarecidamente que le agregues una imagen a tu pokemon")]
        public string strImagen { get; set; }


        [Range(100, 200, ErrorMessage = "No diga mamadas compa, la vida de tu pokemon debe de estar entre 100 y 200 puntos")]
        public byte tnyVida { get; set; }
        public int intTipoPokemon { get; set; }
        public int intAtaque { get; set; }
        public int intAtaqueEsp { get; set; }
    
        public virtual C_tbAtaqueEspecial C_tbAtaqueEspecial { get; set; }
        public virtual C_tbAtaques C_tbAtaques { get; set; }
        public virtual C_tbTipoPokemon C_tbTipoPokemon { get; set; }
    }
}
